#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 28 13:48:43 2020

@author: sjoerd
"""

import xml.dom.minidom

filename = 'testdata.xml'
dom     = xml.dom.minidom.parse(filename)
records = dom.getElementsByTagName('record')

papers  = dict()
papers['paper']=dict()

for i_paper in range(len(records)):
    papers['paper'][0,i_paper] = dict()
    papers['paper'][0,i_paper]['authors']=dict();
    papers['paper'][0,i_paper]['title'] = records[i_paper].getElementsByTagName('title')[0].getElementsByTagName('style')[0].firstChild.data
#    papers['paper'][0,i_paper]['journal'] 
#    papers['paper'][0,i_paper]['year'] 
#    papers['paper'][0,i_paper]['issue'] 
#    papers['paper'][0,i_paper]['first_page'] 
#    papers['paper'][0,i_paper]['last_page'] 
#    papers['paper'][0,i_paper]['url'] 
    recordauthors = records[i_paper].getElementsByTagName('author')
    
   
    for i_author in range(len(recordauthors)):
        authorname = recordauthors[i_author].getElementsByTagName('style')[0].firstChild.data
        papers['paper'][0,i_paper]['authors'][0,i_author]=dict()
        papers['paper'][0,i_paper]['authors'][0,i_author]['surname'] =authorname.split(',')[0]   
        initials=authorname.split(',')[1]
        if len(initials.split('.')[0])>2:    
            initialsnw=''
            for i_ini in range(len(initials.split(' '))-1):
                initialsnw=initialsnw+initials.split(' ')[i_ini+1][0]
                initialsnw=initialsnw+('. ')
            initials=initialsnw
        print(initials)             
        print(authorname.split(',')[0] )
        papers['paper'][0,i_paper]['authors'][0,i_author]['initials']=initials
